### ISSUE TITLE
User report: "Failed to load image" displayed even after image is displayed properly

### ISSUE THREAD

**Issue by dlew** [dlew/android-gfycat#18]
> I'm using Reddit is Fun app and opened gfycat.com links with your app. Gfy's loads and plays correctly but after closing this message appears.

**Comment by ajs124** [comment]
Can confirm. I use RedReader (another reddit client) and the "Failed to load" message appears twoce/in two "layers" but the videos play fine, most of the time.

**Comment by benfrew13** [comment]
I still get the same symptoms that @ajs124 describes in Reddit is Fun. Gfy loads and plays smoothly, but upon backing out, "Failed to Load" appears 2-3 times. Nexus 5X 6.0.1.

**Comment by dlew** [comment]
I'm going to reinvestigate.
